# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.dependency-track.image_ref
        "config" = module.dependency-track.config
        "tags"   = module.dependency-track.tag_list
      }
  })
}

