name             = "kubewatch"
image            = "cgr.dev/chainguard/kubewatch"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/kubewatch.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"