name             = "go"
image            = "cgr.dev/chainguard/go"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/go.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"