name             = "wait-for-it"
image            = "cgr.dev/chainguard/wait-for-it"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/wait-for-it.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"