name             = "promtail"
image            = "cgr.dev/chainguard/promtail"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/promtail.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"