name                = "wavefront-proxy"
image               = "cgr.dev/chainguard/wavefront-proxy"
logo                = "https://storage.googleapis.com/chainguard-academy/logos/wavefront-proxy.svg"
endoflife           = ""
console_summary     = ""
short_description   = "Minimal wavefront-proxy image"
compatibility_notes = ""
readme_file         = "README.md"

upstream_url        = "https://docs.wavefront.com/proxies.html"
