name             = "kyverno"
image            = "cgr.dev/chainguard/kyverno"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/kyverno.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"