name             = "fulcio"
image            = "cgr.dev/chainguard/fulcio"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/fulcio.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"