name             = "{{ .Readme.Name }}"
image            = "cgr.dev/chainguard/{{ .Readme.Name }}"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/{{ .Readme.Name }}.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"