name                = "vertical-pod-autoscaler"
image               = "cgr.dev/chainguard/vertical-pod-autoscaler"
logo                = "https://storage.googleapis.com/chainguard-academy/logos/vertical-pod-autoscaler.svg"
endoflife           = ""
console_summary     = ""
short_description   = "Image to automatically adjust the amount of CPU and memory requested by pods running in the Kubernetes Cluster"
compatibility_notes = ""
readme_file         = "README.md"

upstream_url        = "https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler"
