name             = "redis"
image            = "cgr.dev/chainguard/redis"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/redis.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"