# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.kube-webhook-certgen.image_ref
        "config" = module.kube-webhook-certgen.config
        "tags"   = module.kube-webhook-certgen.tag_list
      }
  })
}

