name             = "ko"
image            = "cgr.dev/chainguard/ko"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/ko.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"