name             = "maven"
image            = "cgr.dev/chainguard/maven"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/maven.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"