# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.runtime.image_ref
        "config" = module.runtime.config
        "tags"   = module.runtime.tag_list
      }
    },
    {
      basename(path.module) = {
        "ref"    = module.sdk.image_ref
        "config" = module.sdk.config
        "tags"   = module.sdk.tag_list
      }
  })
}

