name             = "memcached-exporter"
image            = "cgr.dev/chainguard/memcached-exporter"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/memcached-exporter.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"