name             = "external-secrets"
image            = "cgr.dev/chainguard/external-secrets"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/external-secrets.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"