name             = "paranoia"
image            = "cgr.dev/chainguard/paranoia"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/paranoia.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"