# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.multus-cni.image_ref
        "config" = module.multus-cni.config
        "tags"   = module.multus-cni.tag_list
      }
  })
}

