name             = "aws-load-balancer-controller"
image            = "cgr.dev/chainguard/aws-load-balancer-controller"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/aws-load-balancer-controller.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"