name             = "ruby"
image            = "cgr.dev/chainguard/ruby"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/ruby.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"