name             = "envoy"
image            = "cgr.dev/chainguard/envoy"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/envoy.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"