# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.kuberay-operator.image_ref
        "config" = module.kuberay-operator.config
        "tags"   = module.kuberay-operator.tag_list
      }
  })
}

