name             = "trillian"
image            = "cgr.dev/chainguard/trillian"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/trillian.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"