name                = "zig"
image               = "cgr.dev/chainguard/zig"
logo                = "https://storage.googleapis.com/chainguard-academy/logos/zig.svg"
endoflife           = ""
console_summary     = ""
short_description   = "Minimal image with zig binary."
compatibility_notes = ""
readme_file         = "README.md"

upstream_url        = "https://ziglang.org/"
