name             = "haproxy"
image            = "cgr.dev/chainguard/haproxy"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/haproxy.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"