name             = "rekor"
image            = "cgr.dev/chainguard/rekor"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/rekor.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"