name                = "wasmer"
image               = "cgr.dev/chainguard/wasmer"
logo                = "https://storage.googleapis.com/chainguard-academy/logos/wasmer.svg"
endoflife           = ""
console_summary     = ""
short_description   = "This image contains the `wasmer` tool which can be used to compile or run wasm binaries."
compatibility_notes = ""
readme_file         = "README.md"

upstream_url        = "https://wasmer.io"
