name             = "wasmer"
image            = "cgr.dev/chainguard/wasmer"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/wasmer.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"