# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.dex.image_ref
        "config" = module.dex.config
        "tags"   = module.dex.tag_list
      }
  })
}

