name             = "dex"
image            = "cgr.dev/chainguard/dex"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/dex.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"