# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.newrelic-prometheus.image_ref
        "config" = module.newrelic-prometheus.config
        "tags"   = module.newrelic-prometheus.tag_list
      }
  })
}

