name             = "rqlite"
image            = "cgr.dev/chainguard/rqlite"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/rqlite.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"