name             = "keda"
image            = "cgr.dev/chainguard/keda"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/keda.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"