name             = "mdbook"
image            = "cgr.dev/chainguard/mdbook"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/mdbook.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"