name                = "vela-cli"
image               = "cgr.dev/chainguard/vela-cli"
logo                = "https://storage.googleapis.com/chainguard-academy/logos/vela-cli.svg"
endoflife           = ""
console_summary     = ""
short_description   = "Vela is a Pipeline Automation (CI/CD) framework built on Linux container technology written in Golang."
compatibility_notes = ""
readme_file         = "README.md"

upstream_url        = "https://go-vela.github.io/docs/"
