# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.logstash-oss-with-opensearch-output-plugin.image_ref
        "config" = module.logstash-oss-with-opensearch-output-plugin.config
        "tags"   = module.logstash-oss-with-opensearch-output-plugin.tag_list
      }
  })
}

