name             = "telegraf"
image            = "cgr.dev/chainguard/telegraf"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/telegraf.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"