# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      "buildkit" = {
        "ref"    = module.latest-root.image_ref
        "config" = module.latest-root.config
        "tags"   = module.latest-root.tag_list
      }
  })
}

