# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.bun.image_ref
        "config" = module.bun.config
        "tags"   = ["latest"]
      }
  })
}

