name             = "boring-registry"
image            = "cgr.dev/chainguard/boring-registry"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/boring-registry.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"