# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.argocd-extension-installer.image_ref
        "config" = module.argocd-extension-installer.config
        "tags"   = module.argocd-extension-installer.tag_list
      }
  })
}

