name             = "tekton"
image            = "cgr.dev/chainguard/tekton"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/tekton.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"