ARG BASE=cgr.dev/chainguard/static

FROM cgr.dev/chainguard/rust as build

RUN echo 'fn main() { println!("Hello"); }' > hello.rs
RUN rustc -C target-feature=+crt-static hello.rs

FROM $BASE

COPY --from=build /work/hello /usr/local/bin/
CMD ["hello"]
