name             = "prometheus"
image            = "cgr.dev/chainguard/prometheus"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/prometheus.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"