# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      "tags" = module.cmctl-tagger.imagetags
    },
    {
      for k, v in module.tagger : k => {
        "tags" = v.imagetags
      }
  })
}

