name             = "cert-manager"
image            = "cgr.dev/chainguard/cert-manager"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/cert-manager.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"