name             = "hugo"
image            = "cgr.dev/chainguard/hugo"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/hugo.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"