name             = "nats"
image            = "cgr.dev/chainguard/nats"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/nats.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"