name             = "influxdb"
image            = "cgr.dev/chainguard/influxdb"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/influxdb.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"