name             = "gitness"
image            = "cgr.dev/chainguard/gitness"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/gitness.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"