name                = "vt"
image               = "cgr.dev/chainguard/vt"
logo                = "https://storage.googleapis.com/chainguard-academy/logos/vt.svg"
endoflife           = ""
console_summary     = ""
short_description   = "Minimal image with the Virus Total CLI - `vt-cli`."
compatibility_notes = ""
readme_file         = "README.md"

upstream_url        = "https://virustotal.github.io/vt-cli/"
