name                = "wolfi-base"
image               = "cgr.dev/chainguard/wolfi-base"
logo                = "https://storage.googleapis.com/chainguard-academy/logos/wolfi-base.svg"
endoflife           = ""
console_summary     = ""
short_description   = "Base image for the [Wolfi Linux Distribution](https://wolfi.dev)."
compatibility_notes = ""
readme_file         = "README.md"

upstream_url        = "https://wolfi.dev"
