name             = "wolfi-base"
image            = "cgr.dev/chainguard/wolfi-base"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/wolfi-base.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"