name             = "mariadb"
image            = "cgr.dev/chainguard/mariadb"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/mariadb.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"