name             = "pgbouncer"
image            = "cgr.dev/chainguard/pgbouncer"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/pgbouncer.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"