# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.confluent-kafka.image_ref
        "config" = module.confluent-kafka.config
        "tags"   = module.confluent-kafka.tag_list
      }
  })
}

