# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.next.image_ref
        "config" = module.next.config
        "tags"   = module.next.tag_list
      }
    },
    {
      basename(path.module) = {
        "ref"    = module.versioned.image_ref
        "config" = module.versioned.config
        "tags"   = module.versioned.tag_list
      }
  })
}

