name             = "memcached"
image            = "cgr.dev/chainguard/memcached"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/memcached.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"