# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.qdrant.image_ref
        "config" = module.qdrant.config
        "tags"   = module.qdrant.tag_list
      }
  })
}

