name                = "nemo"
image               = "cgr.dev/chainguard/nemo"
logo                = "https://storage.googleapis.com/chainguard-academy/logos/nemo.svg"
endoflife           = ""
console_summary     = ""
short_description   = "NVIDIA NeMo Framework is an end-to-end, cloud-native framework to build, customize, and deploy generative AI models anywhere. To learn more about using NeMo in generative AI workflows, please refer to the [NeMo Framework User Guide](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/starthere/intro.html#:~:text=NVIDIA%20NeMo%20Framework,AI%20model%20architectures.)! NVIDIA NeMo Framework has separate collections for Large Language Models (LLMs), Multimodal (MM), Computer Vision (CV), Automatic Speech Recognition (ASR), and Text-to-Speech (TTS) models. Each collection consists of prebuilt modules that include everything needed to train on your data. Every module can easily be customized, extended, and composed to create new generative AI model architectures."
compatibility_notes = ""
readme_file         = "README.md"
upstream_url        = "https://github.com/NVIDIA/NeMo"