name             = "cluster-autoscaler"
image            = "cgr.dev/chainguard/cluster-autoscaler"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/cluster-autoscaler.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"