name                = "zot"
image               = "cgr.dev/chainguard/zot"
logo                = "https://storage.googleapis.com/chainguard-academy/logos/zot.svg"
endoflife           = ""
console_summary     = ""
short_description   = "Minimal image with [zot](https://github.com/project-zot/zot) binary. **EXPERIMENTAL**"
compatibility_notes = ""
readme_file         = "README.md"

upstream_url        = "https://zotregistry.io"
