# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.cli.image_ref
        "config" = module.cli.config
        "tags"   = module.cli.tag_list
      }
    },
    {
      basename(path.module) = {
        "ref"    = module.exec.image_ref
        "config" = module.exec.config
        "tags"   = module.exec.tag_list
      }
    },
    {
      basename(path.module) = {
        "ref"    = module.workflowcontroller.image_ref
        "config" = module.workflowcontroller.config
        "tags"   = module.workflowcontroller.tag_list
      }
  })
}

