name             = "prometheus-elasticsearch-exporter"
image            = "cgr.dev/chainguard/prometheus-elasticsearch-exporter"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/prometheus-elasticsearch-exporter.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"