name                = "weaviate"
image               = "cgr.dev/chainguard/weaviate"
logo                = "https://storage.googleapis.com/chainguard-academy/logos/weaviate.svg"
endoflife           = ""
console_summary     = ""
short_description   = "Minimal container image for running the weaviate vector database."
compatibility_notes = ""
readme_file         = "README.md"

upstream_url        = "https://weaviate.io"
