name             = "flux"
image            = "cgr.dev/chainguard/flux"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/flux.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"