name             = "traefik"
image            = "cgr.dev/chainguard/traefik"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/traefik.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"