name             = "cadvisor"
image            = "cgr.dev/chainguard/cadvisor"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/cadvisor.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"