name             = "kubectl"
image            = "cgr.dev/chainguard/kubectl"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/kubectl.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"