name             = "jre-lts"
image            = "cgr.dev/chainguard/jre-lts"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/jre-lts.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"