# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.six-dot-two-compat.image_ref
        "config" = module.six-dot-two-compat.config
        "tags"   = module.six-dot-two-compat.tag_list
      }
  })
}

