# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.agent.image_ref
        "config" = module.agent.config
        "tags"   = ["latest"]
      }
    },
    {
      basename(path.module) = {
        "ref"    = module.cluster-agent.image_ref
        "config" = module.cluster-agent.config
        "tags"   = ["latest"]
      }
  })
}

