name             = "karpenter"
image            = "cgr.dev/chainguard/karpenter"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/karpenter.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"