#!/usr/bin/env bash

set -o errexit -o nounset -o errtrace -o pipefail -x

wait_for_pod() {
  kubectl wait pod/"${NAME}"-postgresql-0 --for=condition=Ready --timeout=120s -n "${NAMESPACE}"
}

check_tls() {
  # Add Postgres client utilities
  apk add postgresql-client

  # Copy autogenerated TLS certs
  mkdir -p /certs
  kubectl cp "${NAMESPACE}"/"${NAME}"-postgresql-0:/opt/bitnami/postgresql/certs /certs

  # Forward port
  kubectl port-forward service/"${NAME}"-postgresql -n "${NAMESPACE}" 5432:5432

  # Validate TLS works
  psql host="${NAME}"-postgresql."${NAME}".svc.cluster.local port=5432 \
    sslmode=require sslcert=/certs/tls.crt sslkey=/certs/tls.key sslrootcert=/certs/ca.crt \
    -c SELECT 1
}

# Run tests
wait_for_pod
check_tls
