name             = "jdk-lts"
image            = "cgr.dev/chainguard/jdk-lts"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/jdk-lts.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"