name             = "cc-dynamic"
image            = "cgr.dev/chainguard/cc-dynamic"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/cc-dynamic.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"