# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.solr.image_ref
        "config" = module.solr.config
        "tags"   = module.solr.tag_list
      }
  })
}

