# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.cert-manager-webhook-pdns.image_ref
        "config" = module.cert-manager-webhook-pdns.config
        "tags"   = module.cert-manager-webhook-pdns.tag_list
      }
  })
}

