# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.vault.image_ref
        "config" = module.vault.config
        "tags"   = ["latest"]
      }
    },
    {
      basename(path.module) = {
        "ref"    = module.vault-k8s.image_ref
        "config" = module.vault-k8s.config
        "tags"   = ["latest"]
      }
  })
}

