name             = "vault"
image            = "cgr.dev/chainguard/vault"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/vault.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"