# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = {
    "tags" = merge(module.install-cni-tagger.imagetags, module.operator-tagger.imagetags, module.pilot-tagger.imagetags, module.proxy-tagger.imagetags)
  }
}

