name             = "istio"
image            = "cgr.dev/chainguard/istio"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/istio.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"