# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.temporal-admin-tools.image_ref
        "config" = module.temporal-admin-tools.config
        "tags"   = module.temporal-admin-tools.tag_list
      }
  })
}

