# DO NOT EDIT - this file is autogenerated by tfgen

output "summary" {
  value = merge(
    {
      basename(path.module) = {
        "ref"    = module.newrelic-fluent-bit-output.image_ref
        "config" = module.newrelic-fluent-bit-output.config
        "tags"   = module.newrelic-fluent-bit-output.tag_list
      }
  })
}

