name             = "keycloak"
image            = "cgr.dev/chainguard/keycloak"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/keycloak.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"