name             = "kubeflow"
image            = "cgr.dev/chainguard/kubeflow"
logo             = "https://storage.googleapis.com/chainguard-academy/logos/kubeflow.svg"
endoflife        = ""
console_summary  = ""
academy_overview = ""
readme_file      = "README.md"