on:
  pull_request:

permissions: {}

jobs:
  presubmit-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - id: changed
        uses: step-security/changed-files@2e07db73e5ccdb319b9a6c7766bd46d39d304bad # v47.0.5
        with:
          files_yaml: |
            automated:
              - ./images/**
              - ./tflib/**
              - ./.terraform.lock.hcl
              - ./Makefile
              - ./main.tf
              - ./generated.tf
              - ./go.mod
              - ./go.sum
              - ./withdrawn-images.txt
              - ./withdrawn-repos.txt
              - ./reinstated-images.txt

      - if: ${{ steps.changed.outputs.automated == 'true' }}
        run: |
          echo "You have made changes to files that are managed by automation."
          exit 1
