on:
  pull_request:

permissions: {}

jobs:
  presubmit-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - id: changed
        uses: step-security/changed-files@2e07db73e5ccdb319b9a6c7766bd46d39d304bad # v47.0.5
        with:
          files_yaml: |
            automated:
              - ./images/**
              - ./tflib/**
              - ./.terraform.lock.hcl
              - ./Makefile
              - ./main.tf
              - ./generated.tf
              - ./go.mod
              - ./go.sum
              - ./withdrawn-images.txt
              - ./withdrawn-repos.txt
              - ./reinstated-images.txt

      - if: ${{ steps.changed.outputs.automated == 'true' }}
        run: |
          echo "You have made changes to files that are managed by automation."
          exit 1
