on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        default: true
        description: If true, just log

permissions: {}

jobs:
  withdraw:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: chainguard-dev/setup-chainctl@2cddd35a2f120d9973e58094dc6878c93cf58c28 # v0.5.1
        with:
          identity: 720909c9f5279097d847ad02a2f24ba8f59de36a/b6461e99e132298f
      - uses: imjasonh/setup-crane@6da1ae018866400525525ce74ff892880c099987 # v0.5
      - run: |
          for img in $(grep -v '\#' withdrawn-images.txt); do
            if [[ "${{ github.event.inputs.dry_run }}" == "false" ]]; then
              crane delete "$img" || true
              crane delete "$img-dev" || true
            else
              echo "DRY RUN: crane delete $img || true"
              echo "DRY RUN: crane delete $img-dev || true"
            fi
          done
