on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        default: true
        description: If true, just log

permissions: {}

jobs:
  withdraw:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: chainguard-dev/setup-chainctl@2cddd35a2f120d9973e58094dc6878c93cf58c28 # v0.5.1
        with:
          identity: 720909c9f5279097d847ad02a2f24ba8f59de36a/b6461e99e132298f
      - run: |
          while IFS= read -r repo; do
            if [[ "${{ github.event.inputs.dry_run }}" == "false" ]]; then
              chainctl image repo rm "$repo" || true
            else
              echo "DRY RUN: chainctl image repo rm $repo || true"
            fi
          done < <(grep -v '\#' withdrawn-repos.txt)
