on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        default: true
        description: If true, just log

permissions: {}

jobs:
  withdraw:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: chainguard-dev/setup-chainctl@2cddd35a2f120d9973e58094dc6878c93cf58c28 # v0.5.1
        with:
          identity: 720909c9f5279097d847ad02a2f24ba8f59de36a/b6461e99e132298f
      - uses: imjasonh/setup-crane@feee3b6bb0d4c68370f256a4502498c9227e5c6b # v0.7
      - run: |
          while IFS= read -r img; do
            if [[ "${{ github.event.inputs.dry_run }}" == "false" ]]; then
              crane delete "$img" || true
              crane delete "$img-dev" || true
            else
              echo "DRY RUN: crane delete $img || true"
              echo "DRY RUN: crane delete $img-dev || true"
            fi
          done < <(grep -v '\#' withdrawn-images.txt)
